---
- name: Make and execute container
  hosts: all
  become: yes
  vars:
    user: "{{ ansible_user }}"

  tasks:
    - name: Include Docker installation playbook
      include_role:
        name: docker-installation

    - name: Build and run spring boot container
      include_role:
        name: spring

    - name: Build and run cAdvisor container
      include_role:
        name: cadvisor