---
- name: Clone Spring Boot application repository
  git:
    repo: 'https://github.com/S0okJu/OpsAthlan.git'
    dest: /opt/spring-boot-app
    version: sc/1

- name: Build Spring Boot application using Gradle
  command: ./gradlew clean build
  args:
    chdir: /opt/spring-boot-app/scenario_01/spring_echo

- name: Copy Dockerfile for Spring Boot
  copy:
    src: Dockerfile
    dest: /opt/spring-boot-app/scenario_01/spring_echo/Dockerfile

- name: Build Docker image for Spring Boot application
  docker_image:
    path: /opt/spring-boot-app/scenario_01/spring_echo
    name: echo-springboot-app:latest

- name: Run Spring Boot container
  docker_container:
    name: sc1-springboot-app
    image: echo-springboot-app:latest
    state: started
    ports:
      - "8080:8080"