---
- name: Make and execute container
  hosts: all
  become: yes
  vars:
    user: "{{ ansible_user }}"

  tasks:
    - name: Include Java installation playbook
      include_role:
        name: java-installation

    - name: Include Docker installation playbook
      include_role:
        name: docker-installation

    - name: docker-compose
      include_role:
        name: docker-compose
